class CfgPatches
{
	class NLD2035_Characters
	{
		units[]=
		{
			"B_NAF_Soldier_NFP_Tan",
			"B_NAF_Soldier_NFP_Tan_Rolled",
			"B_NAF_Soldier_NFP_Tan_Shirt",
      "B_NAF_Soldier_Woodland",
			"B_NAF_Soldier_Woodland_Rolled",
			"B_NAF_Soldier_Woodland_Shirt",
      "B_NAF_Soldier_Jungle",
			"B_NAF_Soldier_Jungle_Rolled",
			"B_NAF_Soldier_Jungle_Shirt",
      "B_NAF_Soldier_Desert",
			"B_NAF_Soldier_Desert_Rolled",
			"B_NAF_Soldier_Desert_Shirt",
      "B_NAF_AssaultPack_Desert",
      "B_NAF_AssaultPack_Jungle",
      "B_NAF_AssaultPack_multi",
      "B_NAF_AssaultPack_woodland",
      "B_NAF_Kitbag_Desert",
      "B_NAF_Kitbag_Jungle",
      "B_NAF_Kitbag_multi",
      "B_NAF_Kitbag_woodland",
      "B_NAF_Bergen_Desert",
      "B_NAF_Bergen_Jungle",
      "B_NAF_Bergen_multi",
      "B_NAF_Bergen_woodland",
      "B_NAF_Bergen_olive",
      "B_NAF_Bergen_tan"
		};
		weapons[]=
		{
      "NAF_Uni_NFP_Green",
			"NAF_Uni_NFP_Green_Rolled",
			"NAF_Uni_NFP_Green_Shirt",
      "NAF_Uni_NFP_Tan",
			"NAF_Uni_NFP_Tan_Rolled",
			"NAF_Uni_NFP_Tan_Shirt",
      "NAF_Uni_Woodland",
			"NAF_Uni_Woodland_Rolled",
			"NAF_Uni_Woodland_Shirt",
      "NAF_Uni_Jungle",
			"NAF_Uni_Jungle_Rolled",
			"NAF_Uni_Jungle_Shirt",
      "NAF_Uni_Desert",
			"NAF_Uni_Desert_Rolled",
			"NAF_Uni_Desert_Shirt",
      "V_NAF_PC_Lite_Multi",
      "V_NAF_PC_Rig_Multi",
      "V_NAF_PC_Rig_Spec_Multi",
      "V_NAF_PC_Lite_Olive",
      "V_NAF_PC_Rig_Olive",
      "V_NAF_PC_Rig_Spec_Olive",
      "V_NAF_PC_Lite_Tan",
      "V_NAF_PC_Rig_Tan",
      "V_NAF_PC_Rig_Spec_Tan",
      "H_NAF_Viper_Green",
		  "H_NAF_Viper_Tan",
		  "H_NAF_MICH_Desert",
		  "H_NAF_MICH_Jungle",
		  "H_NAF_MICH_Woodland",
		  "H_NAF_Cap_Desert",
		  "H_NAF_Cap_Jungle",
		  "H_NAF_Cap_Woodland",
		  "H_NAF_Cap_Green",
		  "H_NAF_Cap_Tan",
		  "H_NAF_Cap_Multi",
		  "H_NAF_Boonie_Desert",
		  "H_NAF_Boonie_Jungle",
		  "H_NAF_Boonie_Woodland",
		  "H_NAF_Boonie_Green",
		  "H_NAF_Boonie_Tan",
		  "H_NAF_Boonie_Multi"
		};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"A3_Data_F_Enoch_Loadorder"
		};
	};
};

#include "cfgVehicles.hpp"
#include "cfgWeapons.hpp"
